export PS1='${debian_chroot:+($debian_chroot)}\u@\H:\[\033[1;32m\]\w:\[\033[7m\]\$\[\033[0m\] '
# Setting VISUAL with weird command to work around bash functions not being
# exported to sh, which is used by crontab. Fallout from shellshock.
export HISTCONTROL=ignoreboth:erasedups FCEDIT=vim VISUAL='bash -c "vim \$0 \$@"'
export EDITOR="$VISUAL"
