let f=$ESH_HOME."/core/gpg.vimrc"
" note: @% is the current file
if filereadable(f) && @% != ""
  exe 'source '.f
  " vim 7.x seems to require re-loading the buffer, thus edit command here
  edit
endif
map <c-v> :let @"=system("_esh_b zGetCb")<cr>:if col("$")-col(".")==1<bar>call feedkeys("p")<bar>else<bar>call feedkeys("P")<bar>endif<bar>redraw<bar>echon "Pasted " len(@") " characters"<cr>
" vnoremap: "v" visual mode, "nore" no recurse, "map" map
" here we remap control-c to copy the current visual selection to the OS clipboard
vnoremap <c-c> y:call system("cp2cb",@")<cr>:echon "Copied " len(@") " characters"<cr>
if @% =~ "passwords.gpg$"
  " when editing the passwords file, remap * to copy the current work to OS clipboard
  " use the expand() function to highlight the current word (cword)
  " nmap: "n" normal mode
  nmap <buffer> * :let @/=expand("<cword>")<cr>hevb<c-c>
endif
colorscheme elflord
syntax enable
set cursorline noswapfile number hlsearch incsearch sw=2 ignorecase wrap nocompatible ruler ai nocindent indentexpr= showmatch modeline modelines=5 nobackup nowritebackup textwidth=0 expandtab formatoptions=croql wildmenu wildignore=*.class path=.,,** nojoinspaces scrolloff=0
filetype indent off
if exists("my_find")
  call feedkeys(":find ".my_find."\<tab>","t")
endif
