#! /usr/bin/env bash
ESH_HOME=$(dirname $(perl -MCwd -e 'print Cwd::abs_path shift' $0))
escreen_branch=$(cd $ESH_HOME && git rev-parse --abbrev-ref HEAD)
suffix=-$escreen_branch
[ $escreen_branch = master ] && suffix=""
ESH_TMP=/tmp/esh$suffix
[ ! -d $ESH_TMP ] && mkdir $ESH_TMP && chmod 1777 $ESH_TMP
ESH_USER=$USER
exec env -i ESH_HOME=$ESH_HOME ESH_TMP=$ESH_TMP ESH_USER=$ESH_USER $(which node) $ESH_HOME/server.js
