#! /usr/bin/env bash
# old:
#exec node $ESH_HOME/client.js "$@"

source $(dirname $0)/esh-init-common

source $ESH_HOME/esh-init
read ESH_TERM_AUTH_TOKEN < <(ESH_TERM_AUTH_TOKEN=x _esh_b registerTerminal $$ $(tty))
_esh_i $ESH_STY ESH_PORT
e=$(ESH_TERM_AUTH_TOKEN=$ESH_TERM_AUTH_TOKEN _init_ctx -d $ESH_STY $ESH_PORT exec bash)
eval "$e"
