#! /usr/bin/env node
// vim:filetype=javascript
// To do:
//   change auth token every X hours
//   strip whitespace from functions
//
//var opt = require('node-getopt');
//require('shelljs/global');
var util=require('util');
var fs=require('fs');
var path=require('path');
var zlib=require('zlib');
var net=require('net');
var crypto=require('crypto');
var child_process = require('child_process');
var ESH_TMP="/tmp/esh";
var ESH_CORE_FCN_PREFIX="_";

var esh = {
  authToken : "",
  getProfileDir : function() {return util.format("%s/profile.lenio",this.eshHome)},
  handlers : [],
  eshRcFile : util.format("%s/.eshrc",process.env.HOME),
  getCachedFcnlistFile : function() {
    return util.format("%s/%s.fcnlist",ESH_TMP,process.env.USER);
  },
  getFcnlist: function() {
    var list=[];
    var dirs=new Array(
      this.getProfileDir(),
      this.getCoreDir()
    );
    for (var i in dirs) {
      var dir=dirs[i];
      var ls=fs.readdirSync(dir);
      for (var j=0; j<ls.length; j++) {
        if (ls[j].search('^\\w+$')<0) continue;
        if (list.indexOf(ls[j])>=0) continue;
        if (ls[j]=="README") continue;
        list.push(ls[j]);
      }
    }
    return list.join("\n");
  },
  eshHome : path.dirname(process.argv[1]),
  getCachedBashrcFile : function() {
    return util.format("%s/%s.bashrc",ESH_TMP,process.env.USER);
  },
  getBashrc : function() {
    var f=util.format("%s/bashrc",this.getProfileDir());
    var s="";
    if (fs.existsSync(f)) {
      s=fs.readFileSync(f);
    }
    return s;
  },
  getCachedCoreFile : function() {
    return util.format("%s/%s.core",ESH_TMP,process.env.USER);
  },
  getCoreDir : function() {
    return util.format("%s/core",this.eshHome);
  },
  getCore : function() {
    var dir=this.getCoreDir();
    var ls=fs.readdirSync(dir);
    var s="";
    for (var i=0; i<ls.length; i++) {
      if (ls[i].search("^"+ESH_CORE_FCN_PREFIX)<0) continue;
      s+=fs.readFileSync(dir+"/"+ls[i]);
    }
    return s;
  },
  computeHash : function(s) {
    var h = crypto.createHash('sha1');
    h.update(s);
    return h.digest('hex').toLowerCase();
  },
  computePassword : function(s) {
    // MY_PASSWORD should be defined in esh.eshRcFile
    return this.computeHash( MY_PASSWORD + s ).substr(0,6);
  },
  generateAuthToken : function() {
    return crypto.randomBytes(3).toString('hex');
  },
  getZlib : function() {
    return zlib.createGzip({level:zlib.Z_BEST_COMPRESSION});
  },
  getSource : function(key) {
    var buf="";
    if (key=="core") {
      buf=this.getCore();
    } else if (key=="bashrc") {
      buf=this.getBashrc();
    } else if (key=="fcnlist") {
      buf=this.getFcnlist();
    } else {
      var dirs=new Array(
        this.getProfileDir(),
        this.getCoreDir()
      );
      for (var i in dirs) {
        var f=util.format("%s/%s",dirs[i],key);
        if (fs.existsSync(f)) {
          buf=fs.readFileSync(f);
          break;
        }
      }
    }
    return buf;
  }
};

if (fs.existsSync(esh.eshRcFile)) {
  eval(fs.readFileSync(esh.eshRcFile).toString());
} else {
  console.log( "Please create " + esh.eshRcFile + ", with MY_PASSWORD value." );
  process.exit(1);
}

esh.registerHandler=function(evt_id,f) {
  esh.handlers[evt_id]=f;
};

// Bootstrap stage 1
esh.registerHandler( "BS1", function(evt) {
  var s=evt.socket;
  var buf="";
  //buf+="echo 'bootstrapping shell now ...'\n";
  buf+="t="+ESH_TMP+";";
  buf+="[ ! -d $t ] && mkdir $t && chmod 1777 $t;";
  // function _esh_l: load the cached file and eval it
  // arg 1: cache file name
  // optional arg 2: if non-blank, cat the file instead of eval-ing
  buf+='_esh_l() { ' +
    'local f p c;' +
    'f=$1;' +
    'o="openssl enc -a -aes256 -pass pass:$(_esh_b pw ${f/*.})";' +
    // try to use the cached file first ...
    '[ -f $f ] && c="$($o -d -in $f 2>/dev/null)" || ' +
    // cached file does not exist or is expired, so re-cache it
    '{ c="$(_esh_b up ${f/*.})"; echo "$c" | $o >$f; chmod 666 $f; };' +
    //'echo "c:<<$c>>" >&2;' +
    '[ -z "$2" ] && eval "$c" || echo "$c";' +
    '};'
    ;

  buf+='_esh_l ' + esh.getCachedCoreFile() + ';';
  buf+='_esh_l ' + esh.getCachedBashrcFile() + ';';
  buf+=util.format(
    'for f in $(_esh_l %s 1); do _ES_gen_stub $t/%s.f.$f; done;',
    esh.getCachedFcnlistFile(),
    process.env.USER
    );
  buf+='_esh_init;'

  var z=esh.getZlib();
  z.pipe(s);
  z.end(buf);
});

esh.registerHandler( "up", function(evt,key) {
  console.log("up:"+key);
  var s=evt.socket;
  var buf=esh.getSource(key);
  var z=esh.getZlib();
  z.pipe(s);
  z.end(buf);
});

esh.registerHandler( "pw", function(evt,key) {
  var s=evt.socket;
  var buf=esh.computePassword(esh.getSource(key));
  s.end(buf);
});

// receive clipboard data from client, and store inside clipboard
esh.registerHandler( "setCb", function(evt,key) {
  var s=evt.socket;
  var z=zlib.Gunzip();
  var p = child_process.spawn("clipit", [], {stdio:['pipe',process.stdout,process.stderr]});
  p.on('exit',function() {
    console.log("copied "+buf.length+" bytes to clipboard");
  });
  s.pipe(z).pipe(p.stdin);
  // need to send back gzip'd null string, because _esh_b will be attempting to gunzip
  var z1=esh.getZlib();
  z1.pipe(s);
  z1.end("");

  var buf="";
  z.on("data", function(chunk) {
    buf+=new String(chunk);
  });
});

var server = net.createServer({allowHalfOpen:true}, function (socket) {
  //console.log("Connection from " + socket.remoteAddress + " at " + new Date() );
  socket.setNoDelay(true);
  // Define a little object to capture this event
  var evt = {
    socket : socket,
    getEventType : function(data) {
      var err;
      try {
        var m=new String(data).trim().split(" ");
console.log("m:"+m.join(":"));
        if (m[0]!=esh.authToken) {
          console.log("ERROR: unmatched auth token");
          setTimeout( function() { socket.end("bad auth token"); }, 5000 );
          return;
        }
        evt.evt_id = m[1];
        m.splice(0,2);
        // Call the handler
        esh.handlers[evt.evt_id](evt,m);
      } catch (err) {
        console.log( "EXCEPTION: data:" + data + "Message: " + err );
      }
    },
  };
  socket.once("data",evt.getEventType);
  socket.on("end", function() {
    //console.log( "END of socket" );
  });
});

server.listen(0, "localhost", null, function(e) {
  esh.port = server.address().port;
  esh.authToken = esh.generateAuthToken();
  console.log("esh server listening on port=%s, auth token=%s",esh.port,esh.authToken);
  var bash = child_process.spawn("bash", [
    "-c",
    util.format(
      // _esh_b is a bootstrap function to request some resource from, or push
      // some data to, the esh server; the esh server responds by sending the
      // response to stdout; by default the server sends the response gzip'd,
      // except for passwords
      'ESH_PORT=%s;' +
      '_esh_b() { exec 3<>/dev/tcp/localhost/$ESH_PORT; echo %s "$*" >&3; [ ! -t 0 ] && cat >&3; [ $1 = pw ] && cat <&3 || gzip -d -c <&3; exec 3>&-; }; eval "$(_esh_b BS1)"; exec bash --norc --noprofile',
      esh.port,esh.authToken )
  ], {
    stdio: 'inherit'
  });

  bash.on('exit', function (e, code) {
    console.log("shutting down esh");
    process.exit();
  });

});
