#! /usr/bin/env bash
basedir=$HOME
cd $basedir
read -e -p "pick a file: " f
eot=$'\x04'
printf %s $eot
f=${f/#\~/$HOME}
if [ -f "$f" ]; then
  if [ ${f:0:1} != / ]; then
    f=$basedir/$f
  fi
  md5=$(openssl md5 "$f")
  md5=${md5##*= }
  size=$(wc -c <"$f")
  size=${size// /}
  printf "E_FILE_INFO|%s|%s|%s\n" "$f" $md5 $size
  exit 0
elif [ "$f" ]; then
  printf "E_NO_SUCH_FILE: %s\n" "$f"
else
  echo "E_CANCELLED"
fi
exit 1
