#!/usr/bin/env bash
set -e
set -o pipefail
port=8888
siriusxmurl=https://raw.githubusercontent.com/andrew0/SiriusXM/master/sxm.py
siriusxmuser=eric@lincware.com

list_channels() {
  python3 - $siriusxmuser $(pw siriusxm:$siriusxmuser) --list < <(curl --silent $siriusxmurl) 2>/dev/null
}

if channels=$(list_channels) && [ $? -ne 1 ]; then
  exit $?
fi

#
# pick 1 line from a list
#
# example usage: 
#
#   file=$(escreen_pick_something "Pick a file:" "$(find $logdir -type f | sort)")
#   [ -f "$file" ] && lwsa_view_file "$file"
#
# return code: >0 a problem occurred; <0 user specifically did not choose anything
#
escreen_pick_something() {
  local tty=$(tty) intro_label="$1" pick_list="$2" i=1 l
  local -a pick_array
  IFS=$'\n' pick_array=($pick_list)
  local indexes=${!pick_array[@]}
  local n=$((${#pick_array[@]}-1))
  pick_list=$(
    echo "$intro_label"
    for ((i=1; i<=$n; i++)); do
      l=${pick_array[$i]}
      printf "%s. %s\n" $(($i+1)) "$l"
    done
  )
  LINES=$(tput lines)
  if [ $((${#pick_array[@]}-2)) -gt $LINES ]; then
    less <<< "$pick_list" >$tty
  else
    echo "$pick_list" >$tty
  fi
  read -p "Enter choice: " choice
  [ -z "$choice" ] && return 1
  ! [[ "$choice" =~ ^[0-9]+$ ]] && return 1
  choice=$(($choice-1))
  if echo $indexes | grep -q -w -- "$choice"; then
    echo "${pick_array[$choice]}"
  else
    return -1
  fi
}

channel=$(escreen_pick_something "Pick a channel:" "$channels" | cut -d' ' -f1)

set +e

python3 - $siriusxmuser $(pw siriusxm:$siriusxmuser) -p $port < <(curl --silent $siriusxmurl) &
python_pid=$!
trap '{
  echo "killing python back end: $python_pid"
  kill $python_pid
}' EXIT INT QUIT
sleep=5
echo "Starting in $sleep seconds ..."
sleep $sleep
vlc http://localhost:$port/$channel.m3u8
