#!/usr/bin/env bash
set -e
set -o pipefail
port=8888
siriusxmurl=https://raw.githubusercontent.com/andrew0/SiriusXM/master/sxm.py
siriusxmuser=eric@lincware.com

list_channels() {
  python3 - $siriusxmuser $(pw siriusxm:$siriusxmuser) --list < <(curl --silent $siriusxmurl) 2>/dev/null
}

if channels=$(list_channels) && [ $? -ne 1 ]; then
  exit $?
fi

channel=$(pick_something "Pick a channel:" "$channels" | cut -d' ' -f1)

set +e

python3 - $siriusxmuser $(pw siriusxm:$siriusxmuser) -p $port < <(curl --silent $siriusxmurl) &
python_pid=$!
trap '{
  echo "killing python back end: $python_pid"
  kill $python_pid
}' EXIT INT QUIT
sleep=5
echo "Starting channel \"$channel\" in $sleep seconds ..."
sleep $sleep
vlc http://localhost:$port/$channel.m3u8
