#! /bin/bash
# Need to run this to get host only network to work with virtualbox guests on OSX
#
# based on notes from:
# http://superuser.com/questions/429405/how-can-i-get-virtualbox-to-run-with-a-hosts-only-adapter
vpn_iface=utun2
vmware_iface=vmnet2
if [ $(uname -s) = Darwin ]; then
  #sudo sysctl -w net.inet.ip.forwarding=1 net.inet.ip.fw.enable=1
  #sudo sysctl -a net.inet.ip.forwarding net.inet.ip.fw.enable
  sudo sysctl -w net.inet.ip.forwarding=1
  sudo sysctl -a net.inet.ip.forwarding
  #sudo pfctl -F all -f /etc/pf.conf
  {
    echo "nat on en0 from vboxnet0:network -> (en0)"
#echo "nat on en0 from $vmware_iface:network -> (en0)"
    # this next one to allow virtualbox guests to communicate to lincware
    # servers when VPN is on
    echo "nat on $vpn_iface from vboxnet0:network -> ($vpn_iface)"
#echo "nat on $vpn_iface from $vmware_iface:network -> ($vpn_iface)"
    # this one to allow asus flip on 192.168.1.102 to go through the router to
    # elmbp and across elmbp's VPN to lincware
    echo "nat on $vpn_iface from en0:network -> ($vpn_iface)"
    #echo "pass in quick proto tcp to any keep state"
    # set up a private static route in the netgear router to pass
    # 192.168.5.0/24 to elmbp's en0 IP address, then this next "pass" rule gets
    # that traffic passed from en0 to vboxnet0
    echo "pass in quick proto { tcp udp } from 192.168.1.0/24 to 192.168.5.0/24 keep state"
#echo "pass in quick proto { tcp udp } from 192.168.1.0/24 to $vmware_iface:network keep state"
    # forward VPN traffic to lincware VPN: also must set up a static route on
    # the router to pass 10.9.0.0/16 to elmbp's en0 IP address
    echo "pass in quick proto { tcp udp } from 192.168.1.0/24 to 10.9.0.0/16 keep state"
  } | sudo pfctl -mf -
  sudo pfctl -e
fi
